bastikr/boolean.py

boolean/boolean.py

Previous:
```python
>>> parse("~A*~(~A+~B)")
AND(NOT(Symbol('A')), NOT(OR(NOT(Symbol('A')), NOT(Symbol('B')))))
```
Now:
```python
>>> parse("~A*~(~A+~B)")
FALSE
```

Literalize terms before starting the simplify.

---

boolean/boolean.py

Evaluating bool(TRUE) should be (and currently) is True, but bool(FALSE) should, I think, also be False, but it isn't. I added bool() (and nozero() for Python 2) to TRUE and FALSE classes. Fixes issue #12

TRUE and FALSE act as booleans

---

boolean/boolean.py

Compatibility with Python 2 was incomplete (It was missing handling Unicode). This PR fixes it.

Python 2 and 3 compatibility: Using basestring for unicode support

---

LICENSE.txt
MANIFEST.in
README.md
boolean/__init__.py
boolean/boolean.py
boolean/test_boolean.py
docs/users_guide.rst
setup.cfg
setup.py

For your consideration:
* Move boolean.py to a proper package with an __init__ 
* Add revised BSD license text and updated notices, for you to review for accuracy
* Create setup.py and config for tests and wheels. Use `python setup.py test` for testing
* Updated README, doc and doctests for Python 2 and 3.

Add setup.py and update doctests to run on Python2.7 and 3.x

---

boolean/boolean.py
boolean/test_boolean.py

I added `&`, `|` and `!` as alternatives for parsing Boolean expressions and `__and__()` and `__or__()` to `Expression` (I print the strings something as `"a&(b|c)"` instead of `"a*(b+c)"` as our developers are more familiar with the `"&"` and `"|"` notation, but supporting both doesn't hurt. Fixes issue #11

Support parsing expression with alternative operators

---

boolean/boolean.py
boolean/test_boolean.py

This PR renames `eval` to a clearer `simplify`. Also removes `evalkwargs` from it.

Rename eval -> simplify

---

boolean/boolean.py

Allow swapping the Symbol class used during parsing. Also, Symbol knows what characters it takes (for me I needed dot, colons and slashes as part of the symbols, so that's what the default Symbol takes too now). This addresses something it was mentioned in issue #9 by @pombredanne.

Allow custom Symbol class

---

boolean/boolean.py

The default value for the eval argument (True) should be consistent across all `__new__()` and `__init__()`. Also, Symbol should only receive one optional positional argument, no more. Added test for that as well.

Consistent eval parameters and allowed arguments

---

boolean/test_boolean.py

I've looked all over the tests and I found only another misuse of `assertTrue()`. I think we'll need to change those to `assertEqual()` later, but I'm waiting until the tokenizer lands (as it adds/touches tests too much). For now, this fixes the current tests.

Fix other misuse of assertTrue()

---

boolean/boolean.py
boolean/test_boolean.py

Improves on what's being commented in issue #12: Expression should evaluate to True/False only when it can do so, otherwise raise an exception.
This patch includes a couple other fixes in the tests (that immediately jumped with the change), which are also addressed in pull request #23

Evaluate expression as boolean

---

boolean/boolean.py
boolean/test_boolean.py

This is rough proof of concept that supports more or less:
* #11 and #18 (alternative operators) 
* #9  (feeding sequences to the parser with via custom tokenizers)
* #19 (custom symbols)
It has these benefits IMHO:
* Use the standard lib "tokenize" module
* Accept arbitrary Python names as symbols
* Support `and`, `not`, `or`, `!`, `~`, `+`, `*`, `&`, `|` as operators in any combination
* Parse comments and multi-line expressions
* Accept any white spaces
* Errors are reported with row and columns
* Accept alternative tokenizer, allowing to have custom 
symbols and operators
* Accept custom symbols class

Alternative parser using a standard tokenizer with multiple customization possible

---

boolean/boolean.py
boolean/test_boolean.py

When starting to use the new library with the changes we've made, I realized custom symbols that take different arguments need to receive variadic arguments in `__new__()`. For consistency, all three `__new__()` were changed.

Variadic arguments for __new__() needed for custom Symbols

---

boolean/boolean.py

This is mostly cosmetic: I removed extraneaous else statements when not needed and related simplifications of returns . I also extracted `rdistributive` as a top level function for clarity

Simplify returns and else when not needed

---

README.md
boolean/__init__.py
boolean/boolean.py
boolean/test_boolean.py
docs/concepts.rst
docs/development_guide.rst
docs/users_guide.rst
setup.py

You cannot pass an expression or a string to the Expression constructor
anymore. Instead you build an Expression (which is really akin to an
algebra definition) and you can build expression with the configured
operations, symbol, base elements, etc. Or invoke `parse` on it to parse
from a string.
Creating an expression no longer invoke `simplify()` by default: it
needs to be called explicitly, though some method still retain a
simplify arg for convenience.
You can configure an Expression by providing alternative classes for
AND,OR,NOT,TRUE,FALSE,Symbol and the tokenizer function. In particular
you can subclass and customize the way expressions are printed or
represented.This supports #36
`parse`, `normalize`, `symbols` (now `build_symbols`) are methods of the
Expression object. `parse` …

#33 Do not use __new__ anymore

---

boolean/boolean.py
boolean/test_boolean.py
setup.py

Incorrect expressions such as `xyz (and foo) raise a TypeError when parsed. While I am not sure this should be an error and would best best handled correctly, this PR now raises a proper ParseError instead

And parsing error

---

boolean/boolean.py
boolean/test_boolean.py

Issue #49 started this, this is the pull request for master branch.
`Expression.subs()` taking a `default` so symbols not defined in substitutions map fallback to that default.

Expression.subs() taking 'default'

---

boolean/boolean.py
boolean/test_boolean.py

Normalize would fail when the given expression didn't contain the AND or
the OR operation for cnf and dnf, respectively. The bug was introduced when
the normalize function was changed to return a boolean expression
instead of a tuple containing the sub-terms.

Fix bug in normalize and write tests.

---

LICENSE.txt
boolean/__init__.py
boolean/boolean.py
boolean/test_boolean.py
docs/development_guide.rst
docs/users_guide.rst
setup.py

Sorry for not making this PR atomic, it is just three small changes together:
1. Fixed all year ranges to end with 2017
2. Fixed a couple small typos in docs
3. Changed one test to use `self.assertRaises`
Now that test will fail if the exception is not raised. And it still checks the `error_code` of the exception (meaning, the test does not just end with a `self.assertRaises`). For details see:
http://stackoverflow.com/a/3166985/1269892
I am thinking about taking part in GSoC17 with AboutCode, possibly with the "porting the license expression library to JavaScript" because I have experience with both python and javascript. Please let me know if there are any other reasonable "steps forward" other than joining mail list/IRC (i.e. some projects rank applicants based on finished commts/PRs) …

Fix minor typos in docs and use self.assertRaises in a test

---

boolean/boolean.py
boolean/test_boolean.py

> A  literal is an a atomic formula or its negation.
`algebra.parse('Not(Not(X))').literals` will now produce `{NOT(Symbol('X'))}`
`algebra.parse('Not(Not(X))').symbols` will now produce `{Symbol('X')}`
Fix for issue #59

Symbol / Literal fix and tests (issue #59)

---

boolean/boolean.py
boolean/test_boolean.py
setup.py

This is a fix for the cases where two expression where built from two different algebras and need to be compared (such as a comparing two simplified versions).
I had add some weird type wrapping in the past for reasons I cannot fathom. These precluded any `isinstance` checks to work as new types were created each time. Removing this wart creates no issue and solves the problem, originally reported as part of https://github.com/nexB/license-expression/issues/21

Proper equivalence

---

boolean/boolean.py
boolean/test_boolean.py

The result of the application of De Morgan's laws on an expression should remain unaltered when the same expression is negated an even number of times. However, this does not hold. This is a (simplistic, tentative) fix for such issue.

Fixing De Morgan's laws effect on double negation propositions

---

boolean/boolean.py
boolean/test_boolean.py

This commit adds a "sort" keyword argument to the simplify() function of
the DualBase class. This allows simplification of boolean algebra
expressions to be completed correctly, but does not sort the final
expression. This is needed for various applications where maintaining order matters.
Signed-off-by: Steven Esser <sesser@nexb.com>

Add sort keyword argument to DualBase simplify()

---

boolean/boolean.py
boolean/test_boolean.py

Here is a proposed way to handle issue #86.

Allow a custom set of characters in a token

---

boolean/boolean.py
boolean/test_boolean.py

The `dual` member of operators is assumed to be a class. However, for `TRUE` and `FALSE`, it is an object.
This leads to errors with `simplify()` or `literalize()` within the `demorgan()` method when applied on `TRUE` or `FALSE` objects (e.g., #85)
There are two ways of fixing this: either assign the dual member of `TRUE` and `FALSE` to the corresponding class, or add a `__call__` method to these objects returning themselves.
This PR adopts the latter approach to respect as much as possible the singleton design pattern.

Fix dual for _TRUE and _FALSE

---

boolean/boolean.py
boolean/test_boolean.py

This addresses the case where we have an expression which is small when normalized, but in its current form contains large dual expressions. The blowup happens at the `_rdistributive` step, so the idea is to normalize subexpressions as much as possible before that. Closes https://github.com/bastikr/boolean.py/issues/106
The current test case takes 0.4s with the new code, but took 500s with the old code. We have many of these cases in our codebase and the blow-up is exponential in the size of the original expression. We have tested and this now has reasonable performance with all formulas from our codebase.
The original expression which drew our attention to this issue (below) now takes 30s (~3s under pypy) with the new code and never returns (in fact I run out of memory) with the old …

Performance: prevent blowup in normalization

---

.github/workflows/test-and-build.yml
.gitignore
boolean/__init__.py
boolean/boolean.py
docs/Makefile
docs/api/boolean.rst
docs/api/modules.rst
docs/conf.py
docs/index.rst
setup.py

Adds an API reference to the documentation. Useful for https://github.com/nexB/license-expression/pull/74 to reference from license-expression to boolean.py.
/cc @pombredanne

doc: add API reference

---

.github/workflows/pypi-release.yml
.github/workflows/test-and-build.yml
boolean/boolean.py
setup.py
tox.ini

Using NotImplemented in a boolean context will now raise a TypeError. It had previously raised a DeprecationWarning since Python 3.9.
Fixes: https://github.com/bastikr/boolean.py/issues/121

Workaround incompatibility with Python 3.14

---

.github/workflows/pypi-release.yml
CHANGELOG.rst
setup.py

This PR is to prepare version 5.
See changelog and commits for details:
- https://github.com/bastikr/boolean.py/compare/v4.0...prep-5.0

Prepare V 5.0
